language: php
install:
  - pear install package2.xml
matrix:
  include:
  - php: 5.2
    dist: precise
  - php: 5.3
    dist: precise
  - php: 5.4
    dist: trusty
  - php: 5.5
    dist: trusty
  - php: 5.6
    dist: trusty
sudo: false
script: phpunit tests/
